name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - '**.puml'

permissions:
  contents: write

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Get changed UML files
        id: getfile
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep .puml | xargs)" >> $GITHUB_OUTPUT

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg docs/designs/*.puml
          # args: -v -tsvg ${{steps.getfile.outputs.files}}

      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: 'Generate SVG files for PlantUML diagrams'
          branch: ${{ github.head_ref }}
